---
name: Build and Push
on: push

env:
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/engine

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build the Docker container image
        run: docker build -t ${IMAGE_BASE}:${GITHUB_SHA}
      - name: Push commit image
        run: docker push ${IMAGE_BASE}:${GITHUB_SHA}
      - name: Push branch image
        run: |
          export GITHUB_BRANCH=${GITHUB_REF:%refs/heads/*}
          export DOCKER_BRANCH_TAG=${GITHUB_BRANCH//\//-}
          docker tag ${IMAGE_BASE}:${GITHUB_SHA} ${IMAGE_BASE}:${DOCKER_BRANCH_TAG}
          docker push ${IMAGE_BASE}:${DOCKER_BRANCH_TAG}
      - name: Push latest image
        if: GITHUB_REF == "refs/heads/main"
        run: |
          docker tag ${IMAGE_BASE}:${GITHUB_SHA} ${IMAGE_BASE}:latest
          docker push ${IMAGE_BASE}:latest
